### ISSUE TITLE
Using this fork of rosetta drone effectively disables the rear LED on the mini 2

### ISSUE THREAD

**Issue by lmore377** [m4xw/rosettadrone_mini2#1]
**Describe the bug**
Immediately after tapping open in rosetta drone, the rear led turns off and won't turn back on unless the firmware is downgraded and upgraded with DJI Assistant.

**To Reproduce**
1. Connect the remote to the phone and allow rosetta drone to connect to it
2. Tap open in the app. The rear LED on the drone should almost immediately turn off and it'll stay off even across cold reboots and battery pulls.

**Expected behavior**
The rear LED should be on / flashing to show the current status of the drone

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a 5G
 - OS: Android 11

**Additional context**
The only fix I could find is reinstalling the firmware completely. This can be done by installing DJI Assistant from [here](https://www.dji.com/mini-2/downloads), changing `upgrade_enable` in `C:\Program Files (x86)\DJI Product\DJI Assistant 2 (Consumer Drones Series)\DJIEngine\defaultsettings.ini` to 1, then downgrading the firmware to any older version then upgrading it if you want. Clicking refresh on the current firmware version doesn't work.

**Comment by m4xw** [comment]
Sounds like a parameter is set wrong?
Might be related to mavic air 2 logic. Tbh I cant say i ever noticed that and never had to refresh either.
Try just changing the color in the DJI Fly app next time, I usually switch to rosetta after takeoff, maybe it only happens if u start through it?

**Comment by lmore377** [comment]
Changing the color changes the front LED perfectly fine but the rear LED stays off. I haven't tried switching to Rosetta drone after takeoff but I'll try it and see what happens.

**Comment by m4xw** [comment]
lmk how it goes. Alternatively can spoof as mini 1, but then the UX SDK controls dont let u select certain stuff and we would need custom UI elements (sdk calls still succeed)

**Comment by m4xw** [comment]
(Also i think just "Write default parameters" in Dronehacks should do the job as well, refresh shouldnt be needed, probably fucks with a bitmask)

**Comment by lmore377** [comment]
I'm not sure what's going on but now it's crashing with this error when I tap open in the app. It's happening on my Pixel and a Lenovo tablet with an Android 10 GSI. I don't know if this is related but on the main window it says Model Not Available and Unknown Aircraft.

```
AndroidRuntime: Process: sq.rogue.rosettadrone, PID: 18105
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{sq.rogue.rosettadrone/sq.rogue.rosettadrone.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
AndroidRuntime:        at sq.rogue.rosettadrone.DroneModel.initFlightController(DroneModel.java:264)
AndroidRuntime:        at sq.rogue.rosettadrone.DroneModel.<init>(DroneModel.java:219)
AndroidRuntime:        at sq.rogue.rosettadrone.MainActivity.onCreate(MainActivity.java:589)
ActivityTaskManager:   Force finishing activity sq.rogue.rosettadrone/.MainActivity
ActivityTaskManager:   Force finishing activity sq.rogue.rosettadrone/.ConnectionActivity
ActivityManager: Showing crash dialog for package sq.rogue.rosettadrone u0
```

**Comment by lmore377** [comment]
It turns off the LED even if I connect after takeoff. Also now that I know about dronehacks I was able to find the parameter that messes it up. `g_config.misc_cfg.forearm_lamp_ctrl` is 255 by default but rosetta drone changes it to 1 and I guess that's not a valid value.

**Comment by lmore377** [comment]
It's no problem at all! I like messing around with the drone anyways so this is fun to me. I'm not sure if you already knew this but apparently you can connect to the drone thru USB after takeoff and read parameters while it's hovering lmao.

**Comment by m4xw** [comment]
Lol what? Viable info mate!

**Comment by lmore377** [comment]
Yeah you just gotta get it into that usb mode where it exposes the serial ports, unplug the cord from the computer and let the controller connect, then just take off and reconnect usb afterwards. I'll send a video in a bit

**Comment by m4xw** [comment]
we've been looking at getting usb comms working after launch of payloads, so this is very interesting

**Comment by m4xw** [comment]
Btw did u have issues with video feed? I had to rework it all because its super buggy on my S21.
Works ok on my S6 Edge Plus but still sometimes loses a keyframe.
As far i can tell, need to wait for a SDK update, so curious about other phones (tho should always be in VLOS anyway ;) )

**Comment by lmore377** [comment]
Yeah I've been having problems. The video is just completely black at first but switching between video and photo mode a few times in the app gets it working sometimes but other times it'll just show random blocks of pixels. Also I could never get it to stream video anywhere else but I couldn't get it working with a phantom I had access to for a bit either so it might just be a me problem lol.

**Comment by lmore377** [comment]
Here's the video: https://photos.app.goo.gl/iUEn9adkHKLW6A5W7

**Comment by m4xw** [comment]
> 
> 
> Yeah I've been having problems. The video is just completely black at first but switching between video and photo mode a few times in the app gets it working sometimes but other times it'll just show random blocks of pixels. Also I could never get it to stream video anywhere else but I couldn't get it working with a phantom I had access to for a bit either so it might just be a me problem lol.

I can reproduce those issues on my S6, that gives me hope that I can fix that stuff.
It would be easy if i can request a keyframe, but that is just missing from the android sdk (its available in SDK v5 and IOS SDK v4) so all i can do is wait or waste hours... lol
Rn its as stable is i was able to get it.

https://github.com/m4xw/rosettadrone_mini2/commit/e896debc275cf43edc379c1ea897c16471688d18 was before i rewrote it to use ffmpeg for decoding, notsure if that changes things. would need to cherrypick the other changes tho

**Comment by m4xw** [comment]
@lmore377 can you check if camera still works in the app when doing this?

> 
> 
> Here's the video: https://photos.app.goo.gl/iUEn9adkHKLW6A5W7

**Comment by lmore377** [comment]
Gotta go to the store for a bit but I'll try it when I get back. Here's the full quality upload since Google photos is being ass https://mega.nz/file/xtUCyZCa#_VVH7TDc9CpKNsRI54J1qLeZ06lDp9LW9azM09mXm1I

**Comment by lmore377** [comment]
@m4xw The camera immediately cuts out when plugging in USB in both dji fly and rosetta but telemetry comes through fine and it comes back when you disconnect USB. DJI Fly shows these errors when its plugged in.

**Comment by lmore377** [comment]
![Screenshot_20210921-184313.png](https://user-images.githubusercontent.com/24685455/134265995-f381bbfe-111c-4c97-8a7f-847d2733a8a6.png)![Screenshot_20210921-184403.png](https://user-images.githubusercontent.com/24685455/134266002-c8432826-78f9-48a9-987e-58f8de721607.png)

**Comment by lmore377** [comment]
Also, in rosetta the stream comes back fine with some minor glitchiness so I'm thinking the video stream is still active but no data is being pushed through it when it disables the camera.

**Comment by lmore377** [comment]
And one more thing, when USB is plugged in all battery info disappears in dji fly

**Comment by m4xw** [comment]
> 
> 
> Also, in rosetta the stream comes back fine with some minor glitchiness so I'm thinking the video stream is still active but no data is being pushed through it when it disables the camera. Is there any way to manually request a single parameter from the drone instead of having to refresh the entire list every time? And is there any way to get parameters remotely? I want to see what (if anything) is different between the usb being connected and disconnected.

Its because its not getting a full frame. Thats how the encoding works. If you add correct data on borked data, its gonna get funky


> 
> 
> And one more thing, when USB is plugged in all battery info disappears in dji fly



> 
> 
> @m4xw The camera immediately cuts out when plugging in USB in both dji fly and rosetta but telemetry comes through fine and it comes back when you disconnect USB. DJI Fly shows these errors when its plugged in.

Yea... thanks for confirming

**Comment by lmore377** [comment]
If you start recording before you plug the drone in it'll keep recording perfectly fine. https://mega.nz/file/owNAnJCA#um2rHyIobABQftNXP_XppWN9Fm6rUvnhXAe_fLJbG_I
