### ISSUE TITLE
Outdated version of Gradle

### ISSUE THREAD

**Issue by patogit** [m4xw/rosettadrone_mini2#11]
I have installed Android Studio, and installed everything it asked me to install, and the project has done its "Gradle sync", and now Android Studio says:
> To take advantage of the latest features, improvements, and security fixes, we strongly recommend that you upgrade the Android Gradle Plugin in this project (rosettadrone_mini2) from the current version 3.6.4 to version 7.0.4.

Should Gradle Plugin be updated or not?

**Comment by m4xw** [comment]
Whatever really.

**Comment by m4xw** [comment]
Will consider it when i update stuff
