### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by patogit** [m4xw/rosettadrone_mini2#13]
> 19:11	Executing tasks: [:app:assembleDebug] in project /home/user/experiments/rosettadrone_mini2
> 19:12	Gradle build failed in 1 m 54 s 762 ms

I'm new to Android Studio, and don't know much about the guts of compiling software. Where can I find more useful information besides "failed"?

I also see this under Problems:
> Cannot resolve symbol '@string/google_key'

And Build Output has a few things:
```
> Task :app:processDebugResources FAILED
AGPBI: {"kind":"error","text":"Android resource linking failed","sources":[{"file":"/home/user/experiments/rosettadrone_mini2/app/src/main/AndroidManifest.xml","position":{"startLine":115,"startColumn":8,"endLine":117,"endColumn":49}}],"original":"/home/user/experiments/rosettadrone_mini2/app/src/main/AndroidManifest.xml:116:9-118:50: AAPT: error: resource string/google_key (aka sq.rogue.rosettadrone:string/google_key) not found.\n    ","tool":"AAPT"}
```
```
Android resource linking failed: /home/user/experiments/rosettadrone_mini2/app/src/main/AndroidManifest.xml:116:9-118:50: AAPT: error: resource string/google_key (aka sq.rogue.rosettadrone:string/google_key) not found.
```
```
Android resource linking failed
/home/user/experiments/rosettadrone_mini2/app/src/main/AndroidManifest.xml:116:9-118:50: AAPT: error: resource string/google_key (aka sq.rogue.rosettadrone:string/google_key) not found.
```
```    
> Task :app:externalNativeBuildDebug FAILED
Build djivideojni_armeabi-v7a
ninja: Entering directory `/home/user/experiments/rosettadrone_mini2/app/.cxx/cmake/debug/armeabi-v7a'
[1/2] Building C object CMakeFiles/djivideojni.dir/src/main/cpp/dji_video_jni.c.o
In file included from ../../../../src/main/cpp/dji_video_jni.c:4:
In file included from ../../../../src/main/cpp/ffmpeg.h:34:
In file included from ../../../../src/main/cpp/cmdutils.h:28:
In file included from ../../../../src/main/cpp/include/libavcodec/avcodec.h:31:
In file included from ../../../../src/main/cpp/include/libavutil/samplefmt.h:24:
In file included from ../../../../src/main/cpp/include/libavutil/avutil.h:289:
In file included from ../../../../src/main/cpp/include/libavutil/common.h:401:
In file included from ../../../../src/main/cpp/include/libavutil/mem.h:33:
../../../../src/main/cpp/include/libavutil/error.h:121:5: warning: non-constant static local variable in inline function may be different in different files [-Wstatic-local-in-inline]
    static char str[AV_ERROR_MAX_STRING_SIZE];
    ^
../../../../src/main/cpp/include/libavutil/error.h:119:1: note: use 'static' to give inline function 'av_err2str' internal linkage
av_always_inline char *av_err2str(int errnum) {
^
static 
../../../../src/main/cpp/include/libavutil/attributes.h:37:30: note: expanded from macro 'av_always_inline'
#    define av_always_inline __attribute__((always_inline)) inline
                             ^
1 warning generated.
[2/2] Linking C shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libdjivideojni.so
FAILED: ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libdjivideojni.so 
: && /home/user/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi22 --gcc-toolchain=/home/user/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/user/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libdjivideojni.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libdjivideojni.so CMakeFiles/djivideojni.dir/src/main/cpp/dji_video_jni.c.o  ../../../../src/main/cpp/lib/armeabi-v7a/libffmpeg.so /home/user/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/22/liblog.so -latomic -lm && :
ld: error: ../../../../src/main/cpp/lib/armeabi-v7a/libffmpeg.so:1: unknown directive: version
>>> version https://git-lfs.github.com/spec/v1
>>> ^
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by lmore377** [comment]
Make sure you have [git-lfs](https://git-lfs.github.com/) installed before cloning the repo

**Comment by m4xw** [comment]
Also iirc i only added the for aarch64/armv7a, not x86(64)

**Comment by patogit** [comment]
I have now installed `git-lfs` to see if that helps.

If I need to change something in order to build for `aarch64/armv7a` please explain what to change. I went to Build > Select Build Variant, and I see the option `arm64-v8a` is selected.

Builds keep failing with the same error messages.

The problem seems pretty clearly to be with some Google key. Is it a Google Maps API key? If so, then where am I supposed to put that key? If it's not Google Maps, what is it, how do I get it, and where do I put it?

**Comment by patogit** [comment]
Could the problem be that in Android Studio, under File > Settings... > System Settings > Android SDK, I have API 32 selected? Should I change it to an earlier version?

**Comment by patogit** [comment]
Ok, I fixed this by putting a bogus Google Maps key in the keys.xml file (because I don't care about Google Maps, since I usually fly where there's no internet). I generated my signing key, and use Build > Generate Signed Bundle / APK and choose the APK option (because just plain building failed, complaining about not being signed), and then the build failed with the `version` error mentioned here https://github.com/The1only/rosettadrone/issues/55#issuecomment-805485817 despite having the phone plugged in. So I did the `git lfs clone` steps from https://github.com/The1only/rosettadrone/issues/55#issuecomment-878260282 and the `version` error continues. I tried with both build variants `release` and `debug`.

**Comment by m4xw** [comment]
you'd want `git lfs checkout` iirc as that actually replaces the placeholder files with the actual content.
Sorry didnt get to do much lately so progress has been halted.
Will bring everything up to  date the coming weeks and get rid of the SDK hooks

**Comment by patogit** [comment]
Ok, I finally got this built! The steps:
1. Using Manjaro Linux, install git-lfs package.
2. `git lfs install` # run this anywhere. It must be run once on each machine post-install, otherwise `git lfs` commands fail quietly.
3. `cd your-favorite-directory`
4. `git lfs clone https://github.com/m4xw/rosettadrone_mini2.git`
5. If the previous step doesn't get everything in place, then `cd rosettadrone_mini2 && git lfs checkout`
6. Put the keys.xml file with a DJI key and a Google Maps key (or a fake Google Maps key) in `rosettadrone_mini2/app/src/main/res/values/`
6. Open Android Studio.
7. Open Project, select rosettadrone_mini2.
8. Accept the offer to build the Gradle project, and wait for that to finish.
9. Set up your signing keys, either by following [Android documentation](https://developer.android.com/studio/publish/app-signing) or by going to Build > Generate signed bundle / apk... and choosing APK and following the steps. Honestly, I'm not sure if this step is necessary, since I found it necessary when I was still getting other errors.
9. Build > Make project
10. look for the APK in `rosettadrone_mini2/app/build/outputs/apk/debug/`

**Comment by patogit** [comment]
@m4xw wrote:
>  Will bring everything up to date the coming weeks and get rid of the SDK hooks

This sounds great! Thanks for your effort on this, and I look forward to seeing it even more polished.

**Comment by linus131313** [comment]
> Ok, I finally got this built! The steps:
> 
> 1. Using Manjaro Linux, install git-lfs package.
> 2. `git lfs install` # run this anywhere. It must be run once on each machine post-install, otherwise `git lfs` commands fail quietly.
> 3. `cd your-favorite-directory`
> 4. `git lfs clone https://github.com/m4xw/rosettadrone_mini2.git`
> 5. If the previous step doesn't get everything in place, then `cd rosettadrone_mini2 && git lfs checkout`
> 6. Put the keys.xml file with a DJI key and a Google Maps key (or a fake Google Maps key) in `rosettadrone_mini2/app/src/main/res/values/`
> 7. Plug your Android phone into your computer, and make sure ADB debugging is enabled on the phone. On my Manjaro GNU/Linux system, I plug my phone into my laptop, then I open a console and run `adb devices` and that starts the ADB server. Maybe your machine is different.
> 8. Open Android Studio.
> 9. Open Project, select rosettadrone_mini2.
> 10. Accept the offer to build the Gradle project, and wait for that to finish.
> 11. Set up your signing keys, either by following [Android documentation](https://developer.android.com/studio/publish/app-signing) or by going to Build > Generate signed bundle / apk... and choosing APK and following the steps. Honestly, I'm not sure if this step is necessary, since I found it necessary when I was still getting other errors.
> 12. Build > Make project
> 13. look for the APK in `rosettadrone_mini2/app/build/outputs/apk/debug/`

Hey, ive downloaded RosettaDrone2 for Mini2 and it opens up and connects to my DJI Mini 2. But when I press "open" on the main screen the app crashes. Any ideas why that is, since u've been working with the Mini2 Repository?

**Comment by Sasysan** [comment]
> > Ok, I finally got this built! The steps:
> > 
> > 1. Using Manjaro Linux, install git-lfs package.
> > 2. `git lfs install` # run this anywhere. It must be run once on each machine post-install, otherwise `git lfs` commands fail quietly.
> > 3. `cd your-favorite-directory`
> > 4. `git lfs clone https://github.com/m4xw/rosettadrone_mini2.git`
> > 5. If the previous step doesn't get everything in place, then `cd rosettadrone_mini2 && git lfs checkout`
> > 6. Put the keys.xml file with a DJI key and a Google Maps key (or a fake Google Maps key) in `rosettadrone_mini2/app/src/main/res/values/`
> > 7. Plug your Android phone into your computer, and make sure ADB debugging is enabled on the phone. On my Manjaro GNU/Linux system, I plug my phone into my laptop, then I open a console and run `adb devices` and that starts the ADB server. Maybe your machine is different.
> > 8. Open Android Studio.
> > 9. Open Project, select rosettadrone_mini2.
> > 10. Accept the offer to build the Gradle project, and wait for that to finish.
> > 11. Set up your signing keys, either by following [Android documentation](https://developer.android.com/studio/publish/app-signing) or by going to Build > Generate signed bundle / apk... and choosing APK and following the steps. Honestly, I'm not sure if this step is necessary, since I found it necessary when I was still getting other errors.
> > 12. Build > Make project
> > 13. look for the APK in `rosettadrone_mini2/app/build/outputs/apk/debug/`
> 
> Hey, ive downloaded RosettaDrone2 for Mini2 and it opens up and connects to my DJI Mini 2. But when I press "open" on the main screen the app crashes. Any ideas why that is, since u've been working with the Mini2 Repository?

Hi, linus131313. I have the same problem how do you solve it?

**Comment by stefansommer** [comment]
I solved it by the steps mentioned here https://github.com/m4xw/rosettadrone_mini2/issues/14#issuecomment-1364742735 However, I think there may be other issues as well that are not related to the screen rotation

**Comment by m4xw** [comment]
That fix among others is now upstream as well as a reimpl of my dji waypoint interpreter by one of the new maintainers (@kripper)

Btw @stefansommer i will work on reducing fork distance over time, now that some of the key features of my fork are upstream, so will be porting my video stuff again etc and from there upstream repo becomes more attractive for our purpose again, so we should consider moving the AI stuff there as there seems to be some interest and its now more actively maintained again (For the time being can still only vouch for my impl tho as it is trialed and optimized on real flight data)

But we should def bring everyone together, especially since we all want to have fun with AI ;)

**Comment by Sasysan** [comment]
@m4xw Sorry if i ask you, but there is a difference between this repo and the original repo of The1only?

**Comment by m4xw** [comment]
> @m4xw Sorry if i ask you, but there is a difference between this repo and the original repo of The1only?

Yes many things. Litchi waypoint processor, far more stable video feed, optimized stream duplication to qgc (compatible with many troublesome phones), DJI waypoint interpreter (now upstream as well somewhat) and a bunch of other fixes.
Its getting less and less tho as upstream gets better!

**Comment by stefansommer** [comment]
> Btw @stefansommer i will work on reducing fork distance over time, now that some of the key features of my fork are upstream, so will be porting my video stuff again etc and from there upstream repo becomes more attractive for our purpose again, so we should consider moving the AI stuff there as there seems to be some interest and its now more actively maintained again (For the time being can still only vouch for my impl tho as it is trialed and optimized on real flight data)
> 
> But we should def bring everyone together, especially since we all want to have fun with AI ;)

Yes, definitely. It is great to see upstream being maintained again, I hadn’t noticed that. Should I start an AI thread in upstream to get discussion started?

**Comment by kripper** [comment]
> Should I start an AI thread in upstream to get discussion started?

Yes, please.

**Comment by m4xw** [comment]
agree

**Comment by stefansommer** [comment]
> > Should I start an AI thread in upstream to get discussion started?
> 
> Yes, please.

Here: https://github.com/The1only/rosettadrone/discussions/133
