### ISSUE TITLE
Waypoint Action like START_TAKE_PHOTO not working

### ISSUE THREAD

**Issue by himanshu131098** [m4xw/rosettadrone_mini2#15]
When developing missions with Waypoint Actions like `START_TAKE_PHOTO, START_RECORD, STOP_RECORD` I have observed that this works only with the last waypoint. The actions are not executed in the intermediate waypoints. 

How can we add different waypoint actions? Has anyone developed a solution for this?

Thank You

Himanshu V
Vyorius Drones
New Delhi, India

**Comment by m4xw** [comment]
What is your use-case?
Are you using my DJI Waypoint Translation or the CSV Parser?

**Comment by m4xw** [comment]
Litchi csv parser was implemented here https://github.com/m4xw/rosettadrone_mini2/blob/change_outputsurface/app/src/main/java/sq/rogue/rosettadrone/MainActivity.java#L731-L871

**Comment by himanshu131098** [comment]
I am referring to the `finalizeNewMission()` in the MavlinkReceiver.java. 
https://github.com/m4xw/rosettadrone_mini2/blob/change_outputsurface/app/src/main/java/sq/rogue/rosettadrone/MAVLinkReceiver.java#L550
I think this will convert MAVLINK waypoints to DJI WPS and add the Waypoint actions in it.

**Comment by m4xw** [comment]
Yea it does. I then take the DJI Waypoints and basically run a interpreter on them, manually converting them to "goto"'s and actions for drones that dont actually support native waypoints
IIRC the shenanigans with the intermediate waypoints were only a issue with surveys, hence i asked for your use-case.
I did stub some stuff in 
![image](https://user-images.githubusercontent.com/13141469/168266910-cbcb7273-14c7-48fc-89cd-c13264076be5.png)
https://github.com/m4xw/rosettadrone_mini2/commit/8245d3ad44ec529ed062923a1f7f09c7fa16f283
Might want to doublecheck that behaviour.

Happy to make changes if we clearly define how it functions with real DJI waypoints natively

**Comment by himanshu131098** [comment]
I see you are using a `customWaypointInterpreter` to convert the waypoints into absolute motion commands. 
What I am interested in exploring is that can't use the DJI's `WaypointMissionOperator` with Waypoint actions?

**Comment by m4xw** [comment]
> I see you are using a `customWaypointInterpreter` to convert the waypoints into absolute motion commands. What I am interested in exploring is that can't use the DJI's `WaypointMissionOperator` with Waypoint actions?

The drones I target do not support DJI Waypoint missions.
The base functionality should still be working tho, minus the intermediate wp's for surveys, stubbed that since I externally generate my waypoint lists and then feed it through another program so i just use corridor scan

**Comment by himanshu131098** [comment]
Okay, Understood.
