### ISSUE TITLE
No video on UDP 5600

### ISSUE THREAD

**Issue by laurenweinstein1** [m4xw/rosettadrone_mini2#5]
In the project description it notes:

_View drone video feeds in QGC or forward RTP to an IP address of your choice (currently Mavic Pro 2 only)_

Does the Mavic Pro 2 restriction apply to both UDP 5600 video and RTP? So far using the Mini 2 (emulating Air 2) I can see video in the RD app itself, but have been unable to see any video at all on QGC (or any other UDP video app, either on the same device or an external device). Of course I've set the parameters in QGC properly for UDP video streams on 5600, and I do have the telemetry linkage to QGC -- just no video.

Is there something I'm missing or is this simply not supported yet? Thanks.

**Comment by m4xw** [comment]
I broke that for good when working on the ffmpeg video decoding, but tbh it wasnt properly working prior either (didnt get it working via Mini 2)
Someone needs to take a look.

**Comment by laurenweinstein1** [comment]
I have the video functioning both on QGC localhost and on a remote QGC host. The video is significantly laggy but that's to be expected. Great work!

**Comment by m4xw** [comment]
Hmm I  still get decoding issues with my S21

As for the side notes, yea i am aware. It causes it to send a keyframe (full video frame) instead of a diff and so the video stream can recover. Sadly i cant force it with this SDK to the best of my knowledge. Weirdly enough that behaviour does change once takeoff, i thought maybe its a bw issue on top... got a few other local changes that tweak that behaviour correctly but it made no diff for me.
Feel free to test more and report back.

Also technically its very much possible to have both stream and display, issue rn is the usage of singletons so that stuff needs to be split up into the appropriate instances

**Comment by m4xw** [comment]
@laurenweinstein1 please test videostream_2 branch, video should hopefully now work at the same time as GC!
However it needs to recreate the surface so if u minimize it goes black. I really think i should just switch video -> cam -> whatever target is or smth before each action to ensure....

**Comment by m4xw** [comment]
actually merged. please confirm everything works , if not i reopen

**Comment by m4xw** [comment]
2am here soon, any findings?

**Comment by laurenweinstein1** [comment]
Will build/test sometime over the next few hours (PDT here).

**Comment by laurenweinstein1** [comment]
Hi. I'd call this a regression. Very bad tearing and freezing, without any obvious signs of clearing up over time. No other changes.

**Comment by m4xw** [comment]
> 
> 
> Hi. I'd call this a regression. Very bad tearing and freezing, without any obvious signs of clearing up over time. No other changes.

It clears up if the frame contents change. You cant be possibly moving around the menu enough for this to be a issue, lol.

ffmpeg for android ships without encoders so i cant make easy builds with a transcoder for homecompiler

**Comment by laurenweinstein1** [comment]
Yeah, that's true! So I moved the camera around a lot to try get it to clear, but it just kept tearing up and freezing. The develop version from last night was far more stable and would be usable.

**Comment by m4xw** [comment]
Define stable.

**Comment by laurenweinstein1** [comment]
So long as the video is relatively "stable", most of those other issues are pretty much de minimis. This already goes so far beyond what else is out there. More actions for the waypoints would be fun -- rotate would get my vote -- but really this is doing excellent.

**Comment by m4xw** [comment]
Tbh i am more frustrated the tools doesnt allow us to plan custom actions!
We will need to define a order tho. If a waypoint has a heading, is it when moving to it, or when getting there. what with rotate action, is it before goto starts or when at the target and stuff..
I will ask a bud if he can double check behaviour on the drones that actually support it

**Comment by m4xw** [comment]
I think i can squeeze out a bit more latency wise.
Localhost qgc seems half the latency.
fwiw I dont have a fix for the initial keyframe missing when qgc connects, nothing i can do on my part for now..
Other than recording thousands of packets and keep them in mem

**Comment by m4xw** [comment]
Pushed some more improvements to the branch. Actually seems to still shit itself, but only when flying.
I really wonder if delays cause timing issue & drops for the decoder hmmm

**Comment by laurenweinstein1** [comment]
Lots of trouble with this one. Most of the time no video at all, not on the app and not on local or remote streams. I got the video going a couple of times after lots of restarts of the app -- toggling the photo/video switch didn't seem to make any difference. On those times I got the video, it looked pretty good on the app (very little tearing and only the usual latency) but was freezing up and dropping out completely on QGC both local and remote.

**Comment by laurenweinstein1** [comment]
Huh ... Just for the hell of it, I decided to try the latest Daily Build AppImage of linux UGC -- and it seems to work. Odd, because no less than 2 weeks ago I tried that and it blew up due to 20.04 issues on my 18.04 system. Guess they fixed it.

**Comment by laurenweinstein1** [comment]
Wow the unit gets hot (including the battery of course) when it's just sitting around on even for fairly short periods, but quite hot if on for longer periods sitting on the bench. I mean even sitting there disconnected with the simulator not even running.

So with the new QGC got farther with the simulator. I can successfully launch in the simulator from QGC and I get a simulated hover (at least the telemetry shows about 1.2 meters). I can also simulate landing from QGC, though there is a small oddity -- I have to confirm first on QGC for the landing, and it goes down some, but to complete the landing I also have to confirm on the app to get down the last distance.

When I launch and then try a "go to" in QGC, it switches to guided mode, and I get:

 mission transfer failed. error: vehicle did not respond to mission item communication: guided mode item

I don't see how to get at the log. Where does Download Log put it? 

I can still seemingly upload Missions, and even start them (after takeoff, of course), but then nothing seems to happen other than the mission clock increments -- not even an error.

**Comment by laurenweinstein1** [comment]
Found logs. Will rerun and get you a relevant one ASAP.

**Comment by laurenweinstein1** [comment]
Got back to testing on tablet again. Essentially behaving exactly the same as on the phone. That is, quite well for video now, on app and for local and remote GCS. I haven't been able to capture a log though since that first one -- I must be sequencing something incorrectly -- and I'm not even sure that this particular log has the info needed. "Go to" attempts all fail with the message noted above. If there's a sure fire sequence for grabbing the correct log successfully that would be very handy.

**Comment by laurenweinstein1** [comment]
Getting some logs now. This one attached includes when I was doing several failed "go to" attempts. However, there doesn't seem to be anything related in the log other than "starting absolution mission" -- maybe that's supposed to be "absolute". Anyway, all the go to attempts fail with that error noted above. Having some trouble now with getting video to external QGC but there's probably a setting wrong. But yeah, until go to works waypoints obviously won't work. Takeoff and landing are still OK. All of this is in the simulator, of course.
[bbb.txt](https://github.com/m4xw/rosettadrone_mini2/files/7450727/bbb.txt)

**Comment by m4xw** [comment]
Your goto "error" is not a error.
I told you it will happen and that you can ignore it.
Its executing the mission as per log.
And yea the landing stuff is known.
Are you having your wp's 100 km's apart or smth?
Upload your mission here

**Comment by laurenweinstein1** [comment]
OK, I thought you meant an error on the app for the goto. However, AFAIK I'm not seeing any motion change in the telemetry -- and no visible motion on the map -- for goto or missions. They're just short little vectors around the spot where the sim starts up. I'll look at this again on the latest build on the other device.

**Comment by laurenweinstein1** [comment]
If it's doing goto and missions in the sim there is ZERO indication of this in the telemetry readings or on the map. For the goto, I get the error, but even ignoring it the telemetry stays exactly the same as it was when the launch finished (about 1.2m) and nothing changes. Same for missions. It acts like it started, and if you try to do other things it says a mission is in progress, but neither the app telemetry or map, nor the remote QGC telemetry and map, show changes. It's sitting at the launch altitude without movement. It is possible to then trigger a landing in the sim.

**Comment by m4xw** [comment]
I never had a issue with any of this. Try windows.

**Comment by m4xw** [comment]
Or even latest apk on android works if u dl it directly from their page

**Comment by laurenweinstein1** [comment]
OK, I'll try latest Windows version.

**Comment by m4xw** [comment]
It must send some malformed stuff then, at least for that we expect. Again i never had any issues and another 2 testers had no issues either.
But nobody of them ever tried on linux.

**Comment by m4xw** [comment]
> 
> 
> OK, I'll try latest Windows version.

Thanks, I can really think of no good reason. It tries to execute it, so it must be some bs data or some weird ass state. it makes no sense

**Comment by laurenweinstein1** [comment]
Setting it up right now.

**Comment by m4xw** [comment]
Heres basically what u can expect with my apk: https://m4xw.net/nextcloud/index.php/s/foZNWmeHpk4Rift
Branch doesnt have the turn-to-next-wp yet

**Comment by laurenweinstein1** [comment]
Looking at your video now. I was just writing a note asking exactly what I should expect to see. I just tried from Windows with latest QGC, from Android with latest QGC, and with the last build of yours that I have also of the app, and everything was exactly the same.

**Comment by laurenweinstein1** [comment]
No good. Same results. Acts like it's in a mission, but nothing changes in telemetry or on the map. I'll have to get you a video of what's happening.

**Comment by laurenweinstein1** [comment]
Let me review a couple of things here. 1) Is there any sensitivity to WHERE the simulation run is operating? I've just been building the mission where the simulator starts up somewhere in Norway. 2) I was under the impression that missions would not work unless the simulator thought we were already in the air. So my procedure has been to start RD in sim mode, then drop the safety, and immediately hit takeoff on the app. Then I go to QGC and build and upload a mission for the sim, and start the mission. The mission clock starts running, but the telemetry doesn't change and the map image doesn't change (the altitude correctly shows the 1.2 meters or so from takeoff).

**Comment by laurenweinstein1** [comment]
The latest QGCs seem to have trouble getting the video. Odd, because the older ones handled it perfectly with your later code.

**Comment by m4xw** [comment]
> 
> 
> The latest QGCs seem to have trouble getting the video. Odd, because the older ones handled it perfectly with your later code.

Ohh?

I never got it to work either on that version, thought its smth with my routing (but it made no sense!)
Good info!

**Comment by laurenweinstein1** [comment]
Video isn't working with the current daily Android build either.

**Comment by laurenweinstein1** [comment]
Reverting to the previous Linux AppImage (about a year older than current) brings back the video. Still no luck with missions. They appear to be running but telemetry figures and map images never change.

**Comment by m4xw** [comment]
Do you see it moving on the in-app map screen in rosetta?

**Comment by m4xw** [comment]
or general telemetry for that matter

**Comment by laurenweinstein1** [comment]
Negative. No change in telemetry, no map movement on either QGC or app for missions (or goto). I *DO* see the telemetry change appropriately (on both the app and QGC) for launch and land.

**Comment by laurenweinstein1** [comment]
I'm finding lots of errors like these from QGC that appear to be triggered by mission-related commands:

qrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool
qrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool
fffqrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool
qrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool
qrc:/qml/APMSafetyComponentSummary.qml:85: TypeError: Cannot read property 'enumStringValue' of null
qrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool
qrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool
qrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool
qrc:/qml/QGroundControl/Controls/ToolStrip.qml:100:21: Unable to assign [undefined] to bool

**Comment by laurenweinstein1** [comment]
So here's something interesting. When I use the physical controller in sim mode on the app, I DO get telemetry changes AND map movement. For forward, backward, right, left, up and down, telemetry shows appropriate changes and also for forward, backward, right and left I see appropriate map movement. There's no change on the map for up or down, but that's probably typical for the zoom level. For yaw (again, this is all from the controller) the drone symbol does not rotate, but the yaw clearly has occurred as subsequent forward, backward, etc. movements will show on the telemetry and map appropriately.

**Comment by laurenweinstein1** [comment]
Just tried the virtual joysticks on the latest QGC (the one where the video does *not* work). No effect, the virtual joysticks seem completely inoperative in the sim.

**Comment by laurenweinstein1** [comment]
Physical controller movements in the sim ARE also reflected properly on the connected QGC map.

**Comment by m4xw** [comment]
Can u check if this actually succeeds? https://github.com/m4xw/rosettadrone_mini2/blob/develop/app/src/main/java/sq/rogue/rosettadrone/DroneModel.java#L2250-L2274

**Comment by m4xw** [comment]
In case it never gets there.. whats your android ver?
Try adding 10 instead of 0 at https://github.com/m4xw/rosettadrone_mini2/blob/develop/app/src/main/java/sq/rogue/rosettadrone/DroneModel.java#L2053
https://github.com/m4xw/rosettadrone_mini2/blob/develop/app/src/main/java/sq/rogue/rosettadrone/DroneModel.java#L2279

If this actually works then your fucking android doesnt like  instant scheduled task for whatever fucking reason.
If virtstick fails you got cursed by dji or smth. Write me the exact fc version

**Comment by m4xw** [comment]
Shouldnt be that tho as your log had "motion done" which is in the task.
Only other way would be weird math somewhere, give me some GPS coordinates in a affected area that doesnt leak your stuff

**Comment by laurenweinstein1** [comment]
I had been thinking maybe something was related to location -- like east vs west longitude. But I've tested both at the default location and close to me here in L.A. and the behavior seems the same.

**Comment by laurenweinstein1** [comment]
Both devices are at Android 11. Apparently 12 is coming very soon, I'm going to try block it on both for now. Not necessarily simple to do.

**Comment by m4xw** [comment]
I never tried the default location.. but that code is mostly from upstream so i think they would have

**Comment by laurenweinstein1** [comment]
FC version is: 01.03.0000
RC version is: 04.11.0016

**Comment by m4xw** [comment]
Got your mail etc. I will check it tomorrow or so. done for the day
I sent u mine too

**Comment by laurenweinstein1** [comment]
No difference in behavior at the coordinates you sent me. I'll build in the changes you suggested above.

**Comment by laurenweinstein1** [comment]
OK, so replacing those 0s with 10s had no obvious effect. I do NOT see an error in the on-screen log relating to virtualstick. What I do see (on a 4 to 6 waypoint mission) is:

RTL altitude set to 60m
Smart RTL set to true
Config click
Motion done!
[Motion done! repeats about 25 times (or more!)]
Motion uploaded and ready to execute via VirtStick!
Mission status: 0
Motion done!
[Motion done repeats about 16 times]
Start waypoint mission()
Starting absolution mission
[It seemed to hang there, at that point I switched from video to map and back on the app]
Set small screen
Set main screen
Motion error not support(255)
[Motion error not support(255) repeats about 10 times

**Comment by stefansommer** [comment]
I can't get UDP stream in external QGC. Video works in the app (slightly laggy) and on QGC on the phone (very laggy), external QGC doesn't seem to get video. Telemetry etc. working on the external QGC. Any ideas? (I can post a logcat)
