### ISSUE TITLE
Waypoints from QGC

### ISSUE THREAD

**Issue by tr0043t** [m4xw/rosettadrone_mini2#6]
I'm probably missing something obvious, but so far I've been unable to get waypoints into RD successfully. My assumption has been that one could upload a mission (e.g., from QGC) and then RD would fly them in what amounted to a "Guided" mode since of course waypoints can't be loaded into a Mini 2. However, all of my attempts to upload missions from QGC to RD fail with an error from QGC that the final ack was not received and a log entry in RD that "waypoint coordinate provided is invalid (255)" -- even though the mission waypoints are simple for testing and look fine. So apparently no waypoints or other mission parameters are getting into RD at all. Am I misunderstanding the operational model for using RD with the Mini 2? Thanks.

**Comment by laurenweinstein1** [comment]
Glancing over this quickly, this build doesn't include the new video streaming code, right?

**Comment by patogit** [comment]
@m4xw is this Python script to convert from ArduPilot waypoint format to Litchi CSV useful at all in the effort to make waypoints from QGroundControl work with RosettaDrone? https://github.com/YarostheLaunchpadder/MissionPlanner-to-Litchi

**Comment by patogit** [comment]
My goal is to be able to create and fly mapping missions without internet, so the "upload to Litchi Fly Hub, convert, and download" is not feasible for me, whereas a script or direct compatibility is feasible.
