### ISSUE TITLE
Android 12 and /sdcard, etc.

### ISSUE THREAD

**Issue by laurenweinstein1** [m4xw/rosettadrone_mini2#7]
Android 12 is rolling out faster, and will probably hit my devices sometime soon. It appears that the latest permission changes could impact this code, since the ability to request a previous Android storage permission appears to be removed. This will likely mean changing the existing storage model a bit ...

**Comment by stefansommer** [comment]
The app crashes immediately after launch on my one phone with Android 13. Exact same configuration works on my other phone with Android 9. Is it related to this? I can provide a logcat

**Comment by m4xw** [comment]
> The app crashes immediately after launch on my one phone with Android 13. Exact same configuration works on my other phone with Android 9. Is it related to this? I can provide a logcat

Last develop branch should work now, you might need to follow that workaround for video i outlined in the other issue tho.
Only thing required is to enable the permissions manually first before starting the app (and i had troubles with it being put to sleep with samsung tools, so need to disable that too if you use QGC on your phone as well).

As long the app works in this context i will close this  issue for now @laurenweinstein1 
Someday need to handle it properly tho

**Comment by stefansommer** [comment]
Thanks! I can confirm the crash upon start is fixed (I couldn't get the video to work though, even with the workaround)
