### ISSUE TITLE
Test results!

### ISSUE THREAD

**Issue by tr0043t** [m4xw/rosettadrone_mini2#8]
So I built two versions today. One using straight develop (including your new waypoint action code) and one using videostream rebased over develop.

In static tests (no flights so far) both seemed to function correctly. I tested using a remote QGC. Develop seemed to properly accept uploaded missions from QGC and displayed the video on the RD app. My videostream rebased over develop version (MyTest) streamed video to the remote QGC properly and also appeared to accept mission uploads from QGC correctly.

Excellent!

**Comment by m4xw** [comment]
Simulator works fine here, make sure to configure your start points in the settings

**Comment by laurenweinstein1** [comment]
That sounds very promising! I was just about to start testing the low latency mode on QGC, which I didn't expect to make much difference. I can test today whatever code you have.

**Comment by m4xw** [comment]
Pushed to develop

**Comment by laurenweinstein1** [comment]
Thanks.

**Comment by m4xw** [comment]
Latency feels a bit better to me, hmm

**Comment by m4xw** [comment]
you might notice a change in latency tho

**Comment by laurenweinstein1** [comment]
Yep.
