### ISSUE TITLE
Yaw limits for Gimbal

### ISSUE THREAD

**Issue by patogit** [m4xw/rosettadrone_mini2#9]
Is the lack of a yaw limit something that can be resolved with sufficient programming time? If so, any estimate how much time it might take? Or is it practically impossible to fix?

**Comment by m4xw** [comment]
I cant remember if you can even trigger it in rosetta unless you tell it to.
Its just smth I noticed when trying the DJI Fly app and yes its a simple thing to limit / prevent.

**Comment by m4xw** [comment]
No longer a concern
